spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
        hibernate:
          jdbc:
            time_zone: UTC
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null